services:
  db:
    image: postgres:16
    container_name: ticket-db
    environment:
      POSTGRES_DB: ticketdb
      POSTGRES_USER: ticketuser
      POSTGRES_PASSWORD: password
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  backend:
    container_name: ticket-backend
    build:
      context: ./backend        # ðŸ”¥ HIER war der Fehler
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://ticketuser:password@db:5432/ticketdb
      SECRET_KEY: supersecretkey
    ports:
      - "5000:5000"

  frontend:
    container_name: ticket-frontend
    build:
      context: ./frontend       # ðŸ”¥ NICHT docker/frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
