version: "3.8"

services:
  ticketapp:
    build: .
    container_name: ticketapp
    volumes:
      - ./data:/app/data
    restart: always

  nginx:
    image: nginx:alpine
    container_name: ticket-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ticketapp
